server:
   port: 8888

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: mytest
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://10.168.10.152:3306/lunch
       username: root
       password: wangjie123

mybatis:
    type-aliases-package: com.course.model
    mapper-locations:
       - mapper/*
